### PR TITLE
Use poetry for package management

### PR DESCRIPTION
**Pull request by palango**
Fixes https://github.com/raiden-network/scenario-player/issues/610

The current state of package management was a mess and people got confused on how to install the SP correctly. This fixes that by using poetry to manage the package. This makes it possible to mark raiden as a git dependency and the CI is simplified as well.

@ulope @karlb As this brings in another tool (besides `setup.py` and `pip-tools`) please let me know if you think we should go this way. If so, I'll clean this up a bit more.

### CODE REVIEW

**Comment by ulope** [comment]
I think this repo is a good candidate to try out new tools like this.

Two things that come to mind:
- Does this still support installing Raiden in editable mode?
- The `Makefile` `install` / `install-dev` targets should probably be updated to use `poetry` directly instead of going via pip

**Comment by palango** [comment]
> Does this still support installing Raiden in editable mode?

The only thing I found was `path` dependencies that have a `develop` option which installs the dependency in editable mode: https://python-poetry.org/docs/dependency-specification/#path-dependencies

**Comment by ulope** [comment]
> > Does this still support installing Raiden in editable mode?
> 
> The only thing I found was `path` dependencies that have a `develop` option which installs the dependency in editable mode: https://python-poetry.org/docs/dependency-specification/#path-dependencies

Hm yeah but we probably don't want to assume a filesystem layout.

This does seem to work though:
```shell
$ poetry install
[...]
$ poetry run pip install -Ue ../raiden
[...]
Installing collected packages: raiden
  Found existing installation: raiden 1.1.1.dev270+g4b910649d
    Uninstalling raiden-1.1.1.dev270+g4b910649d:
      Successfully uninstalled raiden-1.1.1.dev270+g4b910649d
  Running setup.py develop for raiden
Successfully installed raiden
```

**Comment by karlb** [comment]
I generally like poetry, but it might not be really mature yet. Since you already did the work and the git dependencies sound great, let's just give it a try!

**Review by ulope — APPROVED** [review]

**Pull request merged**
