### PR TITLE
Adapt makefile and CI config to use poetry

### PR DESCRIPTION
**Pull request by ulope**
Automatically invoke targets in the makefile through poetry

### CODE REVIEW

**Review by palango — APPROVED** [review]
Thanks for fixing this. lgtm.

Regarding the CI failure. Should we remove the lock file form the repo to make it pass those minor updates?

**Comment by palango** [comment]
> Thanks for fixing this. lgtm.
> 
> Regarding the CI failure. Should we remove the lock file form the repo to make it pass those minor updates?

@ulope Opinions on this?

**Comment by ulope** [comment]
Err, strange I thought I already commented here.

I wouldn’t remove the lockfile. Otherwise we’ll be back to non-reproducible builds and could just have kept using pip.

**Comment by ulope** [comment]
Thanks for fixing the PR @palango!

**Pull request merged**
