### PR TITLE
Add interactive wait task

### PR DESCRIPTION
**Pull request by konradkonrad**

### CODE REVIEW

**Review by weilbith — APPROVED** [review]
LGTM 🤣

**Review by ulope — DISMISSED** [review]
This won’t work for multiple reasons:
- `input()` is blocking and will cause greenlets not to run while the prompt is displayed.
- When the UI is in use the prompt may not show up (although the ui could be used to solve this)

**Comment by weilbith** [comment]
I'll fix the formatting with an amended commit and force push. I don't see the reason to first put a fixup commit here.

**Comment by konradkonrad** [comment]
> This won’t work for multiple reasons:
> 
>     * `input()` is blocking and will cause greenlets not to run while the prompt is displayed.

While we're waiting for input, I don't see what kind of background greenlets need to run?
> 
>     * When the UI is in use the prompt may not show up (although the ui could be used to solve this)
I am aware of the UI issue -- the prompt does show up, but it does not look nice and ui rendering is broken afterwards.

**Comment by ulope** [comment]
We clarified this in a call. This is a debugging only feature and therefore it's fine to merge as is.

**Pull request merged**
