### PR TITLE
Add smoketest utility

### PR DESCRIPTION
**Pull request by nlsdfnbch**
Implements #350 .

Touches the following features, testing their defaults:

- [x] Node Setup works (we can fire up a number of raiden nodes for a scenario)
- [x] Node funding works
- [x] udc deposits work
- [x] deploying custom tokens works
- [x] configuring a pfs works
- [x] tear down works (exit code 0)

### CODE REVIEW

**Comment by nlsdfnbch** [comment]
This is meant as a smoketest for the SP - it should confirm most parts of it are working.
I just wanted a pair of eyes to confirm that the intention is clear. 

I've updated the yaml file with a doc string to clear up its purpose.

The only thing I see that isn't tested is the funding of nodes, since we can't provide a stocked wallet with the SP.

**Comment by nlsdfnbch** [comment]
I've updated the PR. This should be taken with a grain of salt, as I think it's quite a lot of staffolding for a sanity check, but alas I suppose it comes with the design of the software.

There now exists a python script at `tests/smoketests/smoketest_launcher.py` which will deploy a custom network, including raiden contracts. It then creates a scenario definiion file from a jinja2 template and runs that scenario.

Finally, it cleans up any generated files.

@yoichi, please have a look at the contract deployment part.

**Comment by pirapira** [comment]
Until the contract fix lands, deployments will fail: https://github.com/raiden-network/raiden-contracts/pull/1313

**Comment by nlsdfnbch** [comment]
After a chat with @konradkonrad , we found a simpler solution to spinning up a private network. An account file has been supplied, which is unlocked using a circleci secret. 

Circle will run the smoke tests against PRs and bumps, to verify the build.

This PRs introduces the changes necessary to make this happen.

**Pull request merged**
